Library.js
AbdelrhmanAmin/Library-js pull request #1
Opened 2021-02-03 00:57 UTC by AbdelrhmanAmin

I've added those features:
 - New book creation.
 - Storage of the boos.
 - Set books as read or unread.
 - Delete books

2021-02-03 09:00 UTC, sumancrest0001 commented
**Status: Changes required :gear:**

**Hello @AbdelrhmanAmin,**
Thank you for submitting this project. You have implemented all the coding requirements from the specifications. But there are few things that need to be addressed before moving ahead. Let's have a look at them.

**[Required]** guideline is not considered while creating the PR. It should contain a title and a short description of the features implemented.  [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)

**[Required]** Commit messages should be capitalized and descriptive. 

**[Required]** You have added the workflow but you seem to forget to add linter configurations. Please check the [reference](https://github.com/microverseinc/linters-config/tree/master/javascript)

2021-02-03 09:01 UTC, sumancrest0001 commented on README.md
> +```
**[Required]** It should be **Library-js**.

2021-02-03 09:06 UTC, sumancrest0001 requested changes
**Please make the required changes and submit for another code review.** 

**If you have any queries regarding this review, message me on slack.
Suman Shrestha**

**Happy coding !!!**

2021-02-03 15:18 UTC, AbdelrhmanAmin commented
@sumancrest0001  I've already added the linters.

2021-02-03 18:14 UTC, christianotieno requested changes
## Changes required ♻️ 
Hello @AbdelrhmanAmin 👋 

The progress made in this project is commendable. We, however, do have some issues to work on before proceeding. 👇 

The changes touch on the use of ES6 arrow functions, as it was already introduced to you in the [previous lesson](https://microverse.pathwright.com/library/javascript-module-v10-copy/166786/path/step/97635162/)([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/es6_requirement.png)), and an issue about an error with book creation.

### Happy coding 💻 
#### Christian Otieno (CR)

2021-02-03 18:14 UTC, christianotieno commented on index.js
> +function getBooks() {
## Implement function with ES6 arrow function
- [ ] Implement this `getBooks` function with ES6 arrow function
```suggestion
const getBooks = () => {
```

After the book has been created, there is no way to display the books in the `localStorage` as there is no way javascript can iterate over the array properly. This is the error we currently have. 👇 
![library-book-creation-error](https://user-images.githubusercontent.com/22345961/106790514-bab32f00-6664-11eb-9651-ac281e3e0685.png)
- [ ] Kindly fix this issue, thank you!

2021-02-03 18:14 UTC, christianotieno commented on index.js
> +function setBooks() {
## Implement function with ES6 arrow function
- [ ] Implement this `setBooks` function with ES6 arrow function
```suggestion
const setBooks = () => {
```

2021-02-03 18:14 UTC, christianotieno commented on index.js
> +function addBookToLibrary(arr, book) {
## Implement function with ES6 arrow function
- [ ] Implement this `addBookToLibrary` function with ES6 arrow function
```suggestion
const addBookToLibrary = (arr, book) => {
```

2021-02-03 18:14 UTC, christianotieno commented on index.js
> +function displayEachBook() {
## Implement function with ES6 arrow function
- [ ] Implement this `displayEachBook` function with ES6 arrow function
```suggestion
const displayEachBook = () => {
```

2021-02-03 18:14 UTC, christianotieno commented on index.js
> +    table.appendChild(tr);
## Modularise this module. 

- [ ] Kindly keep application logic separated from DOM manipulation tasks ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) from Pathwright)
- [ ] While at it, try and keep the number of changes/updates to the DOM as low as possible, they are costly for the browser ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_updates_requirement.png) from Pathwright)

2021-02-04 04:08 UTC, peterrobert approved these changes
### APPROVED 👍🏿 💯 
Hello, @AbdelrhmanAmin  very nice project. I love the design. I also love the way you have easily kept your code simple and working keep up 👍🏿 

### on to the next project 👍🏿  
### HAPPY CODING 💻

2021-02-04 04:10 UTC, merged